version: 2.1

orbs:
  silta: silta/silta@0.1

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Silta build & deploy'
          build_folder: web
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              ignore:
                - production

      - silta/simple-build-deploy:
          # Extend the build-deploy configuration
          <<: *build-deploy
          name: Silta build & deploy to production cluster
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: 
                - production
