version: 2.1

orbs:
  silta: silta/silta@dev:master

workflows:
  version: 2
  build_deploy:
    jobs:
      - silta/simple-build-deploy: &build-deploy
          name: 'Silta build & deploy'
          build_folder: web
          context: 'silta_dev'
          silta_config: silta/silta.yml
          filters:
            branches:
              only:
                - master

      - approval:
          type: approval
          name: "Deployment approval"
          filters:
            branches:
              ignore:
                - production
                - master

      - silta/simple-build-deploy:
          <<: *build-deploy
          requires:
            - "Deployment approval"
          filters:
            branches:
              ignore:
                - production
                - master

      - silta/simple-build-deploy:
          <<: *build-deploy
          name: Silta build & deploy to production cluster
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only:
                - production
